In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from complexcgr import CGR
from pathlib import Path
from sklearn.model_selection import train_test_split
import dask
import dask.dataframe as dd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
from dask import delayed
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
# Process the test data
def label_encoding_dim_category_reduction(df_in,country):
    # Print the processing status with the DataFrame name
    print("Processing DataFrame:", country)
    # Create a custom label encoding map
    custom_encoding_map = {'N': 0, 'A': 1, 'T': 2, 'G': 3, 'C': 4}
#     dropped_columns = ['Isolation source', 'category', 'BioSample', 'sra_accession', 'country']
#     snp_data = df_in.drop(columns=dropped_columns)
    # Apply custom label encoding to categorical columns
    categorical_cols = df_in.select_dtypes(include=['object']).columns
    df_in[categorical_cols] = df_in[categorical_cols].apply(lambda col: col.map(custom_encoding_map))

    # Combine non-categorical variables with informative SNP columns
#     data_combined = pd.concat([category_data[dropped_columns], df_filtered], axis=1)
    return df_in

In [3]:
# Function to process test data and make columns to be common betwrrn test and training data
def process_test_data(input_dataFrame, country):
    # metadata columns
    dropped_columns = ['Isolation source', 'category', 'BioSample', 'sra_accession', 'country']
    y_uganda=input_dataFrame[dropped_columns]
    # Drop unnecessary columns
    training_columns = X.columns.tolist()  # Assuming X is your training data

    # Check for missing columns in test data and add them with zeros
    missing_columns = set(training_columns) - set(input_dataFrame.columns)
    for column in missing_columns:
        input_dataFrame[column] = 0

    # Reorder the columns in the test data to match the training data
    test_data = input_dataFrame[training_columns]

    # Fill missing values (NaN) with zeros
    test_data = test_data.fillna(0)

    # Assuming there's a function called label_encoding_dim_category_reduction
    test_data = label_encoding_dim_category_reduction(test_data, country)
    # Add metadata
    test_data=pd.concat([y_uganda,test_data],axis=1)
    test_data=test_data.drop(columns=["Unnamed: 0"])

    return test_data

In [4]:
# Training data to extract columns
df_chisquare=pd.read_csv("chisquare_training_features_100_final_undersampled_no_corr.csv")
df_chisquare

,Isolation source,category,BioSample,sra_accession,country,305245,2027584,3906518,4027906,4552348,...,4554083,842668,44836,1239006,1922047,2211095,2212974,3051143,2181910,4089957
0,feces swine,swine,SAMN03576991,SRR2847938,kenya,4.0,4.0,0.0,4.0,4.0,...,0.0,4.0,0.0,4.0,4.0,4.0,0.0,0.0,0.0,0.0
1,chicken carcass,poultry,SAMN03577271,SRR3115981,ethipia,4.0,0.0,0.0,4.0,4.0,...,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
2,feces swine,swine,SAMN03577149,SRR3134909,ethipia,4.0,4.0,0.0,4.0,4.0,...,0.0,0.0,0.0,0.0,4.0,4.0,0.0,0.0,4.0,4.0
3,pig stool,swine,SAMN07135217,SRR6951172,nigeria,4.0,4.0,0.0,4.0,0.0,...,0.0,4.0,0.0,4.0,0.0,4.0,0.0,0.0,0.0,4.0
4,poultry,poultry,SAMN06240034,SRR5232014,uganda,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707,feces poultry,poultry,SAMN03577373,SRR6411078,ethipia,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
708,chicken,poultry,SAMN02368606,SRR1106456,nigeria,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
709,pig stool,swine,SAMN07135265,SRR6950720,nigeria,4.0,4.0,0.0,4.0,4.0,...,0.0,4.0,0.0,4.0,0.0,4.0,0.0,0.0,0.0,4.0
710,feces swine,swine,SAMN03577204,SRR3088941,ethipia,4.0,4.0,0.0,4.0,4.0,...,0.0,0.0,0.0,0.0,4.0,4.0,0.0,0.0,4.0,4.0
711,chicken carcass,poultry,SAMN03577058,SRR4243071,ethipia,0.0,4.0,0.0,4.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0

In [5]:
# df.to_csv("updated_merged_training_data.csv")
X=df_chisquare.drop(columns=["category","BioSample","sra_accession","country","Isolation source"])
X

,305245,2027584,3906518,4027906,4552348,1804684,401701,620867,423595,341365,...,4554083,842668,44836,1239006,1922047,2211095,2212974,3051143,2181910,4089957
0,4.0,4.0,0.0,4.0,4.0,0.0,4.0,4.0,0.0,0.0,...,0.0,4.0,0.0,4.0,4.0,4.0,0.0,0.0,0.0,0.0
1,4.0,0.0,0.0,4.0,4.0,4.0,0.0,0.0,0.0,0.0,...,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
2,4.0,4.0,0.0,4.0,4.0,0.0,4.0,4.0,4.0,0.0,...,0.0,0.0,0.0,0.0,4.0,4.0,0.0,0.0,4.0,4.0
3,4.0,4.0,0.0,4.0,0.0,0.0,4.0,4.0,4.0,0.0,...,0.0,4.0,0.0,4.0,0.0,4.0,0.0,0.0,0.0,4.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
708,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
709,4.0,4.0,0.0,4.0,4.0,0.0,4.0,4.0,4.0,0.0,...,0.0,4.0,0.0,4.0,0.0,4.0,0.0,0.0,0.0,4.0
710,4.0,4.0,0.0,4.0,4.0,0.0,4.0,4.0,4.0,0.0,...,0.0,0.0,0.0,0.0,4.0,4.0,0.0,0.0,4.0,4.0
711,0.0,4.0,0.0,4.0,4.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0

In [6]:
#Test data
df_uganda=pd.read_csv("uganda_test_data.csv",low_memory=False)
df_tanzania=pd.read_csv("tanzania_test_data.csv",low_memory=False)
df_ethiopia=pd.read_csv("ethiopia_test_data.csv",low_memory=False)
df_kenya=pd.read_csv("kenya_test_data.csv",low_memory=False)
df_south_africa=pd.read_csv("south_africa_test_data.csv",low_memory=False)
df_tunisia=pd.read_csv("tunisia_test_data.csv",low_memory=False)
df_senegal=pd.read_csv("senegal_test_data.csv",low_memory=False)
df_mauritias=pd.read_csv("mauritias_test_data.csv",low_memory=False)
df_nigeria_bovine=pd.read_csv("nigeria_bovine_test_data.csv",low_memory=False)
df_nigeria_swine=pd.read_csv("nigeria_swine_test_data.csv",low_memory=False)
df_nigeria_poultry=pd.read_csv("nigeria_poultry_test_data.csv",low_memory=False)
df_sa_humna=pd.read_csv("south_africa_human_test_data.csv",low_memory=False)
df_tunisia_human=pd.read_csv("tunisia_human_test_data.csv",low_memory=False)

In [7]:
df_south_africa

,Unnamed: 0,Isolation source,BioSample,sra_accession,country,480,534,646,765,793,...,4562904,4562905,4562908,4562913,4562916,4562919,4585971,4607670,4815481,category
0,6,Poultry (Fecal),SAMN19025316,SRR14434437,south_africa,N,N,N,N,N,...,N,N,N,N,N,N,N,N,N,poultry
1,25,Bovine (Meat),SAMN19025259,SRR14434471,south_africa,G,C,T,T,C,...,N,N,N,N,N,N,N,N,N,bovine
2,14,Poultry (Fecal),SAMN19025305,SRR14434450,south_africa,N,N,N,N,N,...,N,N,N,N,N,N,N,N,N,poultry
3,10,Bovine (Meat),SAMN19025312,SRR14434442,south_africa,N,N,N,N,N,...,N,N,N,N,N,N,N,N,N,bovine
4,0,cow,SAMN11636367,SRR9050339,south_africa,G,C,T,T,C,...,N,N,N,N,N,N,N,N,N,bovine
5,3,Bovine (Meat),SAMN19025264,SRR14434433,south_africa,G,C,T,T,C,...,N,N,N,N,N,N,N,N,N,bovine
6,7,Bovine (Organ),SAMN19025262,SRR14434438,south_africa,G,C,T,T,C,...,N,N,N,N,N,N,N,N,N,bovine
7,42,Bovine (Fecal),SAMN19025257,SRR14434493,south_africa,G,C,T,T,C,...,N,N,N,N,N,N,N,N,N,bovine
8,32,Poultry (Meat),SAMN19025278,SRR14434479,south_africa,G,C,T,N,C,...,N,N,N,N,N,N,N,N,N,poultry
9,17,Bovine (Meat),SAMN19025299,SRR14434456,south_africa,N,N,N,N,N,...,N,N,N,N,N,N,N,N,N,bovine
10,35,Bovine (Meat),SAMN19025274,SRR14434484,south_africa,G,C,T,N,C,...,N,N,N,N,N,N,N,N,N,bovine
11,29,Poultry (Meat),SAMN19025282,SRR14434475,south_africa,G,C,T,N,C,...,N,N,N,N,N,N,N,N,N,poultry
12,37,Bovine (Meat),SAMN19025272,SRR14434486,south_africa,G,C,T,T,C,...,N,N,N,N,N,N,N,N,N,bovine
13,22,Bovine (Meat),SAMN19025289,SRR14434467,south_africa,G,C,T,N,N,...,N,N,N,N,N,N,N,N,N,bovine

In [8]:
# Process the test dataframes
ug_test=process_test_data(df_uganda,"uganda")
tz_test=process_test_data(df_tanzania,"tanzania")
eth_test=process_test_data(df_ethiopia,"ethipia")
keny_test=process_test_data(df_kenya,"kenya")
south_af_test=process_test_data(df_south_africa,"south_africa")
tuni_test=process_test_data(df_tunisia,"tunisia")
senegal_test=process_test_data(df_senegal,"senegal")
mau_test=process_test_data(df_mauritias,"mauritias")
nig_bo_test=process_test_data(df_nigeria_bovine,"nigeria_bovine")
nig_switest=process_test_data(df_nigeria_swine,"nigeria_swine")
nig_pol_test=process_test_data(df_nigeria_poultry,"nigeria_poultry")
south_africa_human_test=process_test_data(df_sa_humna,"south_africa_human")
tunisia_human_test=process_test_data(df_tunisia_human,"tuninisia_human")

Processing DataFrame: uganda

KeyError: "['Unnamed: 0'] not found in axis"

In [ ]:
tunisia_human_test

In [ ]:
# Concatenate all dfs
# Create a list of all the test dataframes
test_dfs = [ug_test, tz_test, eth_test, keny_test, south_af_test, tuni_test, senegal_test, mau_test, nig_bo_test, nig_switest, nig_pol_test, south_africa_human_test, tunisia_human_test]
# Concatenate the test dataframes into one
merged_test_df = pd.concat(test_dfs, ignore_index=True)
merged_test_df

In [ ]:
merged_test_df.to_csv("test_data_all_chisquare.csv",index=False)

In [ ]:
# Test data
df_uganda=pd.read_csv("uganda_test_data.csv",low_memory=False)
# df_tz=pd.read_csv("tanzania_test_data.csv")
# df_test=pd.concat(df_ugands,df_tz)
df_uganda